package com.Dao;

import com.model.CustManager;

public interface CustManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cusmanager
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cusmanager
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    int insert(CustManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cusmanager
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    int insertSelective(CustManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cusmanager
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    CustManager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cusmanager
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    int updateByPrimaryKeySelective(CustManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cusmanager
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    int updateByPrimaryKey(CustManager record);
}