package com.Dao;

import com.model.Customer;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;
import java.util.Map;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    Customer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    int updateByPrimaryKey(Customer record);


    @Select("SELECT *,DATE_FORMAT(applyDate,\"%y-%m-%d %H:%i:%s\") applydate1 FROM t_customer limit #{start},#{count}")
    List<Map> getCustomerPage(@Param("start") Integer  start ,@Param("count") Integer  count);
}