package com.model;

public class Bank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank.id
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank.bankName
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank.address
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank.longitude
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank.latitude
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank.phone
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank.id
     *
     * @return the value of t_bank.id
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank.id
     *
     * @param id the value for t_bank.id
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank.bankName
     *
     * @return the value of t_bank.bankName
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank.bankName
     *
     * @param bankname the value for t_bank.bankName
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank.address
     *
     * @return the value of t_bank.address
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank.address
     *
     * @param address the value for t_bank.address
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank.longitude
     *
     * @return the value of t_bank.longitude
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank.longitude
     *
     * @param longitude the value for t_bank.longitude
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank.latitude
     *
     * @return the value of t_bank.latitude
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank.latitude
     *
     * @param latitude the value for t_bank.latitude
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank.phone
     *
     * @return the value of t_bank.phone
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank.phone
     *
     * @param phone the value for t_bank.phone
     *
     * @mbggenerated Mon Nov 12 11:10:35 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}